object Modules {
    const val DATA_MODEL = ":data:model"
    const val DATA_REPOSITORY = ":data:repository"
    const val DATA_SOURCE_LOCAL = ":data:source:local"
    const val DATA_SOURCE_REMOTE = ":data:source:remote"
    const val DATA_SOURCE_LOCAL_IMPL = ":data:sourceImpl:local"
    const val DATA_SOURCE_REMOTE_IMPL = ":data:sourceImpl:remote"
    const val DATA_SOURCE_RETROSHEET = ":data:sourceImpl:retrosheet"
    const val DOMAIN = ":domain"
    const val PRESENTATION_MAIN = ":presentation:main"
    const val PRESENTATION_TUTORIAL = ":presentation:tutorial"
    const val PRESENTATION_WORK = ":presentation:work"
    const val PRESENTATION_STATISTICS = ":presentation:statistics"
    const val PRESENTATION_HELP = ":presentation:help"
    const val PRESENTATION_DEBUG_MENU = ":presentation:debugMenu"
    const val APP = ":app"
}